### ISSUE TITLE
[Feature request]: Implement system clipboard

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#422]
### Is your feature request related to a problem? Please describe

currently an image (or svg) can't be pasted (using ctrl+v) from system's clipboard.
If I copied an image or  svg from the web or external vectorgraphics editor. 
I should be able to paste it into this app.

### Describe your feature request!

 Implement system clipboard.
 
 This could also be used to 
move images/svgs from one page to another page or from one notebook to another notebook in this app.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
currently the flutter clipboard class only support text: https://api.flutter.dev/flutter/services/ClipboardData-class.html but I found some libs implementing this:
* https://pub.dev/packages/super_clipboard

Otherwise this is the issue on the flutter repo: https://github.com/flutter/flutter/issues/23603

**Comment by CodeDoctorDE** [comment]
For implementation see #446

**Comment by CodeDoctorDE** [comment]
Implemented in 2.0.0-beta.5
