### ISSUE TITLE
[Feature request]: Implement internal clipboard

### ISSUE THREAD

**Issue by claws99** [LinwoodDev/Butterfly#446]
### Is your feature request related to a problem? Please describe

Currently, `cut, copy, paste` don't work for non-text data (objects, images etc). Problem as highligted in #422 is that flutter doesn't grant system clipboard

### Describe your feature request!

As a work around we can implement an internal clipboard which will get such jobs done. And enable us to move content from one page to another page. Or even within notebooks of our app.

Later on, when suitable solution arrives it can be modified to access system clipboard.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I don't think an internal clipboard would be good.
There are a few things:
* What if you copy text from another app. We can only use Clipboard.getData if we want to use the data
* What if you close and reopen the app? We can't save these things on restart and otherwise we can't check if the user has restarted the computer.

I think implementing a lib would be better.
I'm implementing my own libraries here https://github.com/LinwoodDev/dart_pkgs and would put this under my package `lw_sysinfo` where you can get system information (currently only getFonts implemented).
The ffi system works great and for android we can use java or kotlin to implement those.

I think implementing an internal clipboard will need more work instead of just adding these feature to my library natively

**Comment by CodeDoctorDE** [comment]
I tested a bit around and found these things out:

* LibreOffice also uses an internal clipboard (tested on linux)
* Linux/Gtk doessn't allow you to use custom clipboards types (see https://gitlab.gnome.org/GNOME/gtk/-/issues/4087)
  * There is something like a uri string that we can use to encode the object in it but I don't know if it is intended to use it
* Windows allow custom clipboard types (see https://learn.microsoft.com/en-us/windows/win32/dataxchg/clipboard-formats)
* Android has this: https://developer.android.com/reference/android/content/ClipData.Item but I don't see an option to add custom clipboard types there

After investigations, I would try adding an internal clipboard here. We can think about adding an extra system for windows

**Comment by CodeDoctorDE** [comment]
I think we can close this in favor of #422.
This is just an implementation idea and not really a new feature beside the one in #422

**Comment by claws99** [comment]
Finally how was System clipboard implemented?

**Comment by CodeDoctorDE** [comment]
I used the libreoffice system.
I don't use the system clipboard for non-text things.
The only operating system that really supports it is windows.
