### ISSUE TITLE
[Feature request]: allow pasting images

### ISSUE THREAD

**Issue by MrGumpIT** [LinwoodDev/Butterfly#605]
### Describe your feature request!

currently if you take a screenshot it is not possible to paste it into the drawing area on windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
good idea but then we need access to the native clipboard

**Comment by MisterE123** [comment]
I agree that this is a necessary feature.

**Comment by CodeDoctorDE** [comment]
i created an issue on my library that i developed for clipboard: https://github.com/LinwoodDev/dart_pkgs/issues/5

**Comment by CodeDoctorDE** [comment]
or wait, super_clipboard is exactly what i need https://pub.dev/packages/super_clipboard

**Comment by CodeDoctorDE** [comment]
Okay I started implementing it in #651

1. The custom clipboard is not available on android < 6. I will still support android 5 and 5.1 and use the current implementation as fallback.
2. All app specific copy/paste will also be handled by the native clipboard manager and override the current copied data inside the clipboard.
3. I didn't test it, it can work fine now or doesn't work. You can test it under https://butterfly-git-feature-native-clipboard-linwood.vercel.app/

**Comment by MrGumpIT** [comment]
mhh not working

**Comment by MisterE123** [comment]
Yeah not working on Windows.

**Comment by CodeDoctorDE** [comment]
Hello,
Thanks for testing it. I fixed it in the next commit.
I tested it myself on windows 11 with copy/pasting an element and pasting a native image from the clipboard.
It would be nice if you could test it too so I can put it in the next beta.

Here are the links:
- Web: https://butterfly-git-feature-native-clipboard-linwood.vercel.app/
- Native: https://github.com/LinwoodDev/Butterfly/actions/runs/8579883201?pr=651 (once it built, the buttons are at the bottom of the page, you need to be authenticated in github otherwise the buttons doesn't work)

**Comment by CodeDoctorDE** [comment]
Hmm okay, I tested it a bit and native web clipboard isn't possible right now...
But on native platforms on mobile and desktop it should work

**Comment by CodeDoctorDE** [comment]
Added in 2.1.0-beta.5
