### ISSUE TITLE
[Documentation request]: Better tutorials, please!

### ISSUE THREAD

**Issue by derei** [LinwoodDev/Butterfly#639]
I just installed the app on my tablet and started using it. At first, the interface (home page) was a bit confusing, but I tapped on one of the two templates (light/dark) and here I was: I quickly figured out how to use the pen tool, erase, add tools to the toolbar, select what I've drawn...
But about there intuition stopped. I had no clue what else to do. So, I tapped on (?) and landed on Tutorials page. Except there was no tutorial, just brief, vague, and often incomplete descriptions for tools.

- how do I make components?
- what's the deal with packs? After I create one (as in giving it a name and saving it), what do I do next? How do I use/populate it?
- layers use is very non-intuitive
- why all tools have a field for "name" if tapped twice?

I regard myself as fairly technical, familiar with a large variety of softwares and work methods, but this one defeated me.

### **Suggestion:**
**- One or more video tutorials with clear steps to introduce the user into using Linwood Butterfly.**
**- Complete information on what currently is called "Tutorials"**, but which should be called rather "index of tools and functionalities", or simply "help index".

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hello thanks for your request!
Writing documentation is a very long task. I will try my best to write the most important things down there. But I can't write more than that without slowing down the updates.
Because of that, I'm always open for pull requests. The markdown files are in `docs/docs`.
There were already some improvements made in the last week. Try visiting the nightly docs: https://docs.butterfly.linwood.dev/docs/2.1/intro.

1. With the area tool or the select tool, right clicking and then clicking on add to pack
2. You can use them to share not document specfic things and import/export into other documents like components, color palettes or styles
3. Feel free to suggest changes. They are mainly for hiding or showing with the layer navigator page
4. With this you can change the tooltip while hovering over it. In the future you can search for them.

I don't like video tutorials because:

* You can't translate them easily. You need someone who speaks the language very good and make a new video for each language
* You need to have good equipment and quality that it's good for people to see
* You can't search in them like with text content
* If you upload them on youtube for example, you depend on an external service that collects data

**Comment by derei** [comment]
Thank you for the quick response.
I completely understand your position towards video tutorials and YouTube. However, as you know best how you intended this app to be used, a video tutorial (in English, even if not perfect), would be a great starting point.
Yes, it would have a limited audience, but it will provide a starting point for others to spread the knowledge.
Also, it would allow others to contribute more to the documentation, so you can focus on actual app development. But is difficult to contribute to an app which one doesn't fully understand how to use.

Regarding YouTube data collection, for viewing there are options like NewPipe and it's forks.

About creating components, I believe you were referring to using the app with a keyboard and mouse. It's quite difficult to perform a right click with a Samsung S-Pen 😁. From your response, I can assume the app isn't fully adapted to be used without at least a mouse.

**Comment by CodeDoctorDE** [comment]
If have some questions, feel free to join the matrix/discord server.
Yeah, newpipe could help. I'm also thinking about creating an "Asset" repository on github where we can upload all videos and can embed it on the site. Then we don't have any service, only the raw media.
And on touch it's double click. Everything you do with right click with mouse, you can do on mobile with double click

**Comment by CodeDoctorDE** [comment]
I will close this since this isn't really a specific request. I will try to expand the docs and I will merge pull requests that will expand it.
Feel free to ask if you don't understand a specific feature and feel free to add your new knowledge to the wiki.
