### ISSUE TITLE
[Feature request]: Use git as a syncing method

### ISSUE THREAD

**Issue by rong-xiaoli** [LinwoodDev/Butterfly#693]
### Describe your feature request!

As I said, I suggest using git as a syncing method.
Which may act like pulling from a git repo for a period of time, and commit and push for another (maybe longer) period of time. 
The idea comes from [here, obsidian-git](https://github.com/denolehov/obsidian-git).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
This could be a nice addition but I have two things that I want to say:
- First: To add this, we need a git client. Why not using the git installed on the system? Because android doesn't allow this. Then we need to ship a big git client inside the app.
- Second (even bigger): The current file format is zip. Zip cannot work really good with binary data since it doesn't allow showing exact line changes

I have currently no idea how to fix these two things. Feel free to answer here!

**Comment by rong-xiaoli** [comment]
I can't answer these two questions immediately. I suggest remain the issue close as not planned before someone can come up with a new idea.
